### ISSUE TITLE
Additional Oura V2 API Endpoints

### ISSUE THREAD

**Issue by sonmaximum** [hedgertronic/oura-ring#2]
Hi, I just wanted to let the project maintainer know that Oura has implemented a few additional endpoints to their V2 API since the last time this project was updated.

Among the new endpoints are: 
- Daily SPO2
- Rest Mode Period
- Ring Configuration
- Sleep Time

Additionally, entries from existing endpoints have been assigned an `id` value, and can be accessed individually at the endpoints 
/v2/usercollection/{collection name}/{document_id} (e.g. `https://api.ouraring.com/v2/usercollection/daily_activity/2-5daccc095220cc5493a4e9c2b681ca941e'`)

Details are at https://cloud.ouraring.com/v2/docs
Just reporting, in case you want to include these new endpoints.

**Comment by hedgertronic** [comment]
I believe @kalifg implemented all of these in his recent PR. If anything's still missing please let me know.
